# Generated by Django 4.0.5 on 2022-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Text', models.TextField()),
            ],
        ),
    ]
